// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdfpgjvhkgatubraodsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkZnBnanZoa2dhdHVicmFvZHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDE3MjEsImV4cCI6MjA2NDI3NzcyMX0.MGwgglo5UMMYBOUuzaDldjTrtArVqFKGPYmEor1Ro2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);